### ISSUE TITLE
Converting to PSV failed

### ISSUE THREAD

**Issue by Ceriwaen** [Ceriwaen/PyLogParser#4]
```
Found 3 .tar.gz file(s)
Extracted 3 files to folder CLA-COM1502-senE612
Extracted 5 files to folder DEV-600-sen189E
Extracted 16 files to folder OPS-505-senDA5F
Processing CLA-COM1502-senE612\Binlogs\SentinelOne_0.binlog
Converting to PSV...Traceback (most recent call last):
  File "C:\Users\petery\PycharmProjects\PyLogParser\PyLogParser.py", line 242, in <module>
    main()
  File "C:\Users\petery\PycharmProjects\PyLogParser\PyLogParser.py", line 210, in main
    convert_to_psv(parsed_converted_container, parsed_file)
  File "C:\Users\petery\PycharmProjects\PyLogParser\PyLogParser.py", line 87, in convert_to_psv
    for line in source_file:
  File "C:\Users\petery\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 7527: character maps to <undefined>
```

**Comment by Ceriwaen** [comment]
Utilizing the -p argument works around this behavior.
